### ISSUE TITLE
Keywords are highlighted within identifiers on underscore boundaries

### ISSUE THREAD

**Issue by uazu** [abingham/ponylang-mode#10]
I see _use_event with 'use' highlighted, is_null with 'is' highlighted, and reverse_in_place with 'in' highlighted. I stripped down my .emacs file to the bare minimum, but it still does the same. I'm on Emacs 24.4.1 on text console, ponylang-mode package installed using melpa.

**Comment by abingham** [comment]
I'm sure it's some boneheaded regex stuff in the mode rather than anything in your configuration. Thanks for digging a bit, though. I'll look at this when I get a chance (hopefully soon).

**Comment by abingham** [comment]
This should be fixed as of df7536d2b0c55713e66a1f4f2bf0250da2859a80. 

If this works for you, go ahead and close this issue. Thanks for reporting it!

**Comment by uazu** [comment]
It works correctly for me now.  Thanks!

**Comment by abingham** [comment]
Great! Thanks for reporting it.
