### ISSUE TITLE
Install doesn't work

### ISSUE THREAD

**Issue by colin-adams** [abingham/ponylang-mode#11]
I tried:

M-X install-package ponylang-mode 

But I get: [No match]

I have the following in my .emacs:

(require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) ;; You might already have this line

I added it today, I had not heard of melpa before.
What else do I need to do?

**Comment by abingham** [comment]
Huh...that's really weird. I can duplicate this on my machine as well, but I have no idea why. (BTW, I assume you mean `M-x package-install . . .` instead of `M-x install-package . . .`). This seems like it must be a problem in `package` or Melpa, not my mode, but I'd be happy to be proven wrong.

As a workaround, can you use `package-list-packages` and install from there?

**Comment by abingham** [comment]
Ah, wait, I think I see what might be happening. If a package is already installed and has no available upgrade, it appears that `package-install` won't offer it as an option. Very clever...

Did you have `ponylang-mode` already installed?

**Comment by colin-adams** [comment]
No, I didn't have it installed. This is my first attempt (I only got pony
installed today).

**Comment by colin-adams** [comment]
package-list-packages does not show ponylang-mode

**Comment by abingham** [comment]
Have you done a `package-refresh-contents`? You may need this to actually
fetch the index from melpa (and other repos).

**Comment by colin-adams** [comment]
I hadn't.

When I try it seems to hang with a status line message of:

Contacting host: elpa.gnu.org:80

I can telnet into that port, so it's not an internet connectivity option.
I'll keep waiting - maybe it's just a slow server.

**Comment by colin-adams** [comment]
No, it's not actually hanging. It just doesn't seem to have any effect.

Is there a manual way to install? Just copying the .el file somewhere?

**Comment by abingham** [comment]
Yes, you can just put the .el file anywhere that's convenient and load it
however you see fit. I'm a bit surprised about elpa, though.

**Comment by colin-adams** [comment]
I'm giving up on this - it's too hard.

It won't initialize, because it can't find dash. But if I try to install
dash for packages-list-packages (package install won't match it) it says it
is already installed (and I can see it in .emacs.d/elpa).

**Comment by abingham** [comment]
Fair enough.
