### ISSUE TITLE
Always indent `class` at left margin

### ISSUE THREAD

**Issue by abingham** [abingham/ponylang-mode#13]
Per the discussion in #9, it seems that we can simplify the indentation rules for `class` by always giving it zero indentation.

**Comment by abingham** [comment]
@colin-adams Would you say this rule applies to `actor` as well? Any other keywords that should always be zero-indented?

**Comment by abingham** [comment]
I've pushed a change that will indent `class` to the left margin in all cases. Try it out and let me know if it works as you expect: https://github.com/abingham/ponylang-mode/tree/class-indent

**Comment by SeanTAllen** [comment]
@abingham any reason this wasn't merged to master?

From my limited experience, this appears to work better than what is on master.

**Comment by abingham** [comment]
Ah! I was waiting for feedback and kinda forgot about this! Since you say it works better, I'll merge it in. Thanks!

**Comment by SeanTAllen** [comment]
Cool. I'm working on a spacemacs layer for Pony and will switch over to using master once that is merged. I'm using pony every day now so I suspect you'll be getting lots of PRs from me.

**Comment by abingham** [comment]
It's merged. Thanks for kicking me to do this :)

**Comment by SeanTAllen** [comment]
There's going to be more coming. :)
