### ISSUE TITLE
Update to README?

### ISSUE THREAD

**Issue by SeanTAllen** [abingham/ponylang-mode#17]
Can you change the README in this repo to point to the new canonical:

seantallen/ponylang-mode

?

Thanks again for all your work getting us to this point Austin!

**Comment by abingham** [comment]
Do you mean the reference in the elisp comments? I don't see anything in
the Readme itself. I'll be happy to change it, of course.

Also, I think I'll delete me repo so that yours isn't reported as a fork,
ie. it becomes more authoritative.

**Comment by SeanTAllen** [comment]
I meant the top level README but deleting the repo is even more effective. Thanks.
